"""Default RoboTwin evaluation tasks."""
TASKS = (
    "move_stapler_pad", "open_microwave", "hanging_mug", "handover_block",
    "stamp_seal", "put_object_cabinet", "place_mouse_pad", "blocks_ranking_size",
    "place_a2b_right", "place_a2b_left",
)

# Complete task set from the pinned RoboTwin benchmark step-limit manifest.
ALL_TASKS = (
    'adjust_bottle',
    'beat_block_hammer',
    'blocks_ranking_rgb',
    'blocks_ranking_size',
    'click_alarmclock',
    'click_bell',
    'dump_bin_bigbin',
    'grab_roller',
    'handover_block',
    'handover_mic',
    'lift_pot',
    'move_can_pot',
    'move_playingcard_away',
    'move_stapler_pad',
    'hanging_mug',
    'open_laptop',
    'open_microwave',
    'pick_diverse_bottles',
    'pick_dual_bottles',
    'place_a2b_left',
    'place_a2b_right',
    'place_bread_basket',
    'place_bread_skillet',
    'place_can_basket',
    'place_cans_plasticbox',
    'place_container_plate',
    'place_dual_shoes',
    'place_empty_cup',
    'place_fan',
    'place_burger_fries',
    'place_mouse_pad',
    'place_object_basket',
    'place_object_scale',
    'place_object_stand',
    'place_phone_stand',
    'move_pillbottle_pad',
    'place_shoe',
    'press_stapler',
    'put_bottles_dustbin',
    'put_object_cabinet',
    'rotate_qrcode',
    'scan_object',
    'shake_bottle',
    'shake_bottle_horizontally',
    'stack_blocks_three',
    'stack_blocks_two',
    'stack_bowls_three',
    'stack_bowls_two',
    'stamp_seal',
    'turn_switch',
)
